In [1]:
import os
import numpy as np
import pandas as pd
import librosa
import librosa.display
import matplotlib.pyplot as plt
from tqdm import tqdm

In [4]:
# === SETTINGS ===
csv_file = "mel_dataset.csv"
mel_height = 128  # Number of Mel bands
time_steps = None  # We'll infer this from the shape

# === LOAD CSV ===
df = pd.read_csv(csv_file)

# === EXTRACT FEATURES ===
filenames = df['filename'].values
X_flat = df.drop(columns=['filename']).values.astype(np.float32)

# Infer time_steps from shape
num_examples, total_features = X_flat.shape
time_steps = total_features // mel_height

# Reshape flat spectrograms back to 2D
X = X_flat.reshape((num_examples, mel_height, time_steps))

# === OPTIONAL: Add a channel dimension if training with CNN ===
X = X[..., np.newaxis]  # Shape becomes (N, 128, T, 1)

# === Example: Use dummy labels (or load real ones from another CSV) ===
# For now, we use zeros as placeholders
y = np.zeros((num_examples,))  # Replace with actual labels later

# Now X and y are ready for training
print("Loaded dataset:")
print("X shape:", X.shape)
print("y shape:", y.shape)


Loaded dataset:
X shape: (10, 128, 173, 1)
y shape: (10,)


In [3]:
print(mel_spectrogram)

[[-80. -80. -80. ... -80. -80. -80.]
 [-80. -80. -80. ... -80. -80. -80.]
 [-80. -80. -80. ... -80. -80. -80.]
 ...
 [-80. -80. -80. ... -80. -80. -80.]
 [-80. -80. -80. ... -80. -80. -80.]
 [-80. -80. -80. ... -80. -80. -80.]]
